repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-format
      - id: ruff
        name: ruff (lint)
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: mypy-push
        name: mypy (push, strict)
        entry: uv run mypy --config-file=pyproject.toml app manage.py
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
