version: '3.9'

services:
  template:
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Some command, but its a template"
    env_file:
      - .env_defaults
      - .env
    volumes:
      - ./src:/app/code
      - ./shared:/app/shared
      - ./shared/logs:/app/shared/logs

  app:
    container_name: trust_vote_app
    extends:
      service: template
    command: sh -c "alembic upgrade head && python manage.py run-server"
    environment:
      - PYTHONPATH=/app/code/
    ports:
      - "8200:8200"
      - "5678:5678" # port for the debugger
    volumes:
      - ./src:/app/code
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trust_vote_db
    volumes:
      - trust_vote_db:/var/lib/postgresql/data
    ports:
      - "8201:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 2

volumes:
   trust_vote_db:
